# Generated by Django 3.2.4 on 2021-06-09 09:42

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('thumbnail', models.CharField(max_length=250)),
                ('publishedAt', models.DateTimeField()),
                ('tags', django_mysql.models.ListCharField(models.CharField(max_length=25), max_length=2600, size=100)),
            ],
        ),
    ]
