# Generated by Django 3.2.4 on 2021-06-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='publishedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
